=== klei1984/max/assets/files/mission.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"$schema": {
			"type": "string"
		},
		"author": {
			"type": "string"
		},
		"copyright": {
			"type": "string"
		},
		"license": {
			"type": "string"
		},
		"category": {
			"type": "string",
			"enum": [
				"Custom",
				"Training",
				"Campaign",
				"Hot-seat",
				"Multiplayer",
				"Demo",
				"Single Player Scenario",
				"Multiplayer Scenario"
			]
		},
		"mission": {
			"type": "string"
		},
		"hash": {
			"type": "array",
			"items": {
				"type": "string",
				"pattern": "^[a-f0-9]{64}$"
			}
		},
		"title": {
			"type": "object",
			"properties": {
				"text": {
					"type": "object",
					"patternProperties": {
						"^[a-z]{2,3}(-[A-Z]{2})?$": {
							"type": "string"
						}
					},
					"additionalProperties": false
				}
			}
		},
		"description": {
			"type": "object",
			"properties": {
				"text": {
					"type": "object",
					"patternProperties": {
						"^[a-z]{2,3}(-[A-Z]{2})?$": {
							"type": "string"
						}
					},
					"additionalProperties": false
				}
			}
		},
		"intro": {
			"$ref": "#/definitions/narrative_block"
		},
		"victory": {
			"$ref": "#/definitions/narrative_block"
		},
		"defeat": {
			"$ref": "#/definitions/narrative_block"
		},
		"winloss_conditions": {
			"type": "string"
		},
		"game_rules": {
			"type": "string"
		},
		"game_events": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"message": {
						"type": "object",
						"properties": {
							"text": {
								"type": "object",
								"patternProperties": {
									"^[a-z]{2,3}(-[A-Z]{2})?$": {
										"type": "string"
									}
								},
								"additionalProperties": false
							},
							"voice": {
								"type": "object",
								"patternProperties": {
									"^[a-z]{2,3}(-[A-Z]{2})?$": {
										"$ref": "#/definitions/media"
									}
								},
								"additionalProperties": false
							}
						}
					}
				}
			}
		}
	},
	"required": [
		"$schema",
		"author",
		"copyright",
		"license",
		"category",
		"title",
		"description"
	],
	"allOf": [
		{
			"if": {
				"properties": {
					"category": {
						"enum": ["Custom", "Hot-seat", "Multiplayer"]
					}
				}
			},
			"then": {
				"not": {
					"required": [
						"hash",
						"mission"
					]
				},
				"properties": {
					"hash": false,
					"mission": false
				}
			},
			"else": {
				"required": [
					"hash",
					"mission"
				]
			}
		}
	],
	"definitions": {
		"media": {
			"type": "object",
			"properties": {
				"copyright": {
					"type": "string"
				},
				"license": {
					"type": "string"
				},
				"resource": {
					"type": "object",
					"properties": {
						"id": {
							"type": "array",
							"items": {
								"type": "string"
							}
						},
						"file": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					},
					"anyOf": [
						{
							"required": [
								"id"
							]
						},
						{
							"required": [
								"file"
							]
						}
					]
				}
			},
			"required": [
				"resource"
			]
		},
		"narrative_block": {
			"type": "object",
			"properties": {
				"text": {
					"type": "object",
					"patternProperties": {
						"^[a-z]{2,3}(-[A-Z]{2})?$": {
							"type": "string"
						}
					},
					"additionalProperties": false
				},
				"video": {
					"type": "object",
					"patternProperties": {
						"^[a-z]{2,3}(-[A-Z]{2})?$": {
							"$ref": "#/definitions/media"
						}
					},
					"additionalProperties": false
				}
			}
		}
	}
}

=== klei1984/max/assets/files/campaign0001.mission.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"author": "Interplay Productions",
	"copyright": "(c) 1996 Interplay Productions",
	"license": "All rights reserved",
	"category": "Campaign",
	"mission": "SAVE1.CAM",
	"hash": [
		"e25f962bf3dcf478335b3163e755f1d394c64fb1fe9653862bc3d38ae1b8d556"
	],
	"title": {
		"text": {
			"en-US": "Islands in the Sun",
			"fr-FR": "Iles au Soleil",
			"de-DE": "Inseln in der Sonne",
			"it-IT": "Isole nel Sole",
			"es-ES": "Islas en el Sol",
			"ru-RU": "Острова на солнце",
			"hu-HU": "Napfényesben Úszó Szigetek"
		}
	},
	"description": {
		"text": {
			"en-US": "Objective: First mission, the target research station must be intact, and the target eco-spheres destroyed in 30 turns\n\nPlanet: Islandia\nClan: Von Griffin\n\nNotes: The Seven Knights have found some alien artifacts that they are studying at a facility on Islandia. \nYou must take over the planet so that the information can be obtained by the council. This can be done \nthrough destroying their eco-spheres and capturing the research lab intact.\n\n",
			"fr-FR": "Objectif: Première mission, la station de recherche de la cible doit être intacte et les éco-sphères de la cible doivent être détruites en 30 tours.\n\nPlanète: Islandia\nClan: Von Griffin\n\nNotes: Les Sept Chevaliers ont trouvé quelques objets alien qu'ils examinent dans un des bâtiments d'Islandia. Vous devez vous emparer de la planète pour que les informations soient collectées par le conseil. Ceci peut être réalisé si vous détruisez leurs éco-sphères et capturez intact le laboratoire de recherche. \n\n",
			"de-DE": "Ziel: Erste Mission, das Ziel Forschungszentrum muß intakt sein, und das Ziel Ökosphäre innerhalb 30 \nRunden zerstört werden.\n\nPlanet: Islandia\nClan: Von Griffin\n\nAnmerkungen: Die Sieben Ritter haben einige Aliens-Kunstwerke gefunden, die sie in einem Komplex auf \nIslandia untersuchen.\n\nSie müssen den Planeten einnehmen, so daß der Council die Informationen erhalten kann. Dies kann durch\nZerstörung ihrer Ökosphären und Eroberung des intakten Forschungszentrums geschehen.\n\n",
			"it-IT": "Obiettivo: Prima missione, la stazione di ricerche bersaglio deve rimanere intatta; e le ecosfere bersaglio devono essere distrutte.\n\nPianeta: Islandia\nClan: Von Griffin\n\nNote: I Sette Cavalieri hanno trovato alcuni manufatti alieni e li stanno studiando in un centro in Islandia.  Tu devi impadronirti del pianeta in modo che il consiglio possa ottenere tutte le informazioni. Questo può essere fatto distruggendo le loro ecosfere e catturando intatto il laboratorio di ricerche.\n\n",
			"es-ES": "Objetivo: Primera misión: La estación de investigación, debe permanecer intacta; las ecosferas, deben destruirse en 30 turnos.\n\nPlaneta: Islandia\n\nClan: Von Griffin\n\nNotas: Los Siete Caballeros han encontrado artefactos alienígenas que están estudiando en una instalación de Islandia.\n\nDeberás ocupar el planeta para que esta información pueda ser obtenida por el consejo. Esto se puede llevar a cabo destruyendo sus ecosferas y capturando el laboratorio intacto.\n\n",
			"ru-RU": "Цель: Первая миссия,  научно-исследовательская станция должна остаться целой, а вражеская экосфера должна быть уничтожена за 30 ходов\n\nПланета: Исландия\nКлан: Вон Гриф\n\nПримечания: Семь Рыцарей нашли инопланетный артефакт в котором говорится что они родились на этой планете .\nВы должны сделать так чтобы они вам не помешали. Для этого нужно эничтожить их экосферу и захватить их лабораторию  .\n\n",
			"hu-HU": "Cél: Az első hadművelet során a célpontként megjelölt kutatóközpontnak sértetlennek kell maradnia, miközben az ökoszférákat 30 körön belül el kell pusztítani\n\nBolygó: Szigetvilág\nKlán: Griff Vérvonal\n\nMegjegyzés: A Hét Lovag birtokába jutott néhány idegen eredetű lelet, melyeket az szigetvilágbeli létesítményükben tanulmányoznak. A bolygó átvétele elengedhetetlen ahhoz, hogy a Tanács hozzáférjen ezekhez az információkhoz. Az egyetlen járható út, ha megsemmisíted az ökoszféráikat, miközben sértetlenül elfoglalod a kutatóközpontot.\n"
		}
	},
	"intro": {
		"text": {
			"en-US": "We are the Secret Council of Freedom, an organization of M.A.X. Commanders who are devoted to making a place for mankind as an equal member of the Concord. As the members of the Concord have grown more decadent, they have left more analytical and decision-making positions in human hands. At last we are in a position to act. Unfortunately, only four Clans have thrown their support to our efforts: Crimson Path, Musashi, Sacred Eight and Von Griffin. The other four Clans prefer to continue to submit themselves to the whims of our Concord masters.\n\nAs long as the Concord has the ability to destroy the Great Ships that contain the majority of our population and all of our main manufacturing facilities, they have hostages that we cannot endanger. For centuries we have sought some way to safeguard the Great Ships. At last we think we have the way to at least give them a fighting chance.\n\nThe Council has received secret survey reports that there is knowledge of ancient artifacts unknown to the Concord on various planets that are up for dispute. Taking over this knowledge will give us an edge that will allow us to protect the Great Ships and negotiate with the Concord from a position of strength.\n\n",
			"fr-FR": "Nous sommes le Conseil Secret de la Liberté, une M.A.X. organisation de commandants qui sont dévoués à faire une place pour l'humanité en tant que membre de la Concorde. Au fur et à mesure de la décadente expansion de la Concorde, ils ont laissé entre les mains des humains des prises de décision de plus en plus analytiques. Enfin, nous pouvons agir. Malheureusement, quatre Clans seulement nous ont donné leur support à nos effort: La Voie de Colère, Musashi, Les Huits Sacrés et Von Griffin. Les quatres autres Clans préfèrent se soumettre aux caprices de nos maîtres Concorde.\n\nTant que la Concorde peut détruire les Grands Navires qui contient la majorité de notre population et nos usines de construction principales, ils ont des otages que nous ne pouvons point mettre en danger. Pendant des siècles nous avons analysé comment sauver les Grands Navires. Nous pensons enfin que nous pouvons leur donner au moins une chance de combat.\n\nDes infiltrateurs secrets ont reporté au Conseil qu'il y a des trésors ancients non connus de la Concorde sur les différentes planètes en disputes. Prenant compte de cette information, cela nous donnera un avantage pour la protection des Grands Navires et une négotiation avantageuse avec la Concorde.\n\n",
			"de-DE": "Wir sind Mitglieder des geheimen Friedensrat, eine Organisation von M.A.X. \nKommandanten, die einen Sitz für die Menschheit, als gleichwertige Mitglieder des \nConcords, schaffen wollen. Während die Mitglieder des Concords immer dekadenter \nwerden, werden immer mehr analytische Stellen der Menschen überlassen, die die \nEntscheidungen jetzt treffen. Endlich können wir etwas unternehmen. Leider werden wir \nvon nur vier Clans unterstützt: Crimson Weg, Musashi, heilige Acht und von Griffin. \nDie übrigen vier Clans würden lieber unseren Concord-Meistern ihr Schicksal überlassen.\n\nSolange der Concord unsere Riesenschiffe, die den Hauptteil unserer Bevölkerung und \nHerstellungseinrichtungen tragen, zerstören kann, halten sie Geiseln fest, deren Verlust \nwir nicht riskieren können. Jahrhunderte lang suchen wir einen Weg, indem wir die \nRiesenschiffe schützen könnten. Endlich glauben wir, daß wir mindestens die Aussicht \nauf Erfolg haben.\n\nDer Rat erhielte Berichte über uralte, von dem Concord unbekannte Artefakte, die auf \neinigen der umstrittenen Planeten gefunden wurden. Dieses Wissen gibt uns einen \nVorteil, mit dem wir unsere Riesenschiffe schützen und von einer stärkeren Position mit \ndem Concord handeln können.\n\n",
			"it-IT": "Noi siamo il Consiglio segreto della Libertà, un'organizzazione di Comandanti M.A.X. che si sono \nimpegnati a far sì che l'umanità venga accolta su un piede di parità tra i membri della Concordia. Col \ntempo, accentuandosi progressivamente la decadenza dei membri della Concordia, questi hanno sempre più \nspesso lasciato in mani umane le cariche dove più erano richiesti processi analitici e decisionali. Ora \nfinalmente ci troviamo in posizione d'agire. Purtroppo solo quattro Clan si sono schierati dalla nostra parte: \nSentiero Scarlatto, Musashi, I Sacri Otto e Von Griffin. Gli altri quattro Clan preferiscono sottomettersi alle \nbizze di coloro che comandano nella Concordia.\n\nFintanto che la Concordia avrà la capacità di distruggere le Grandi Astronavi che contengono la \nmaggioranza della nostra popolazione e tutti i nostri impianti di produzione, essa disporrà di ostaggi che \nnoi non possiamo mettere in pericolo. Per secoli abbiamo cercato un modo per proteggere le Grandi \nAstronavi. Adesso riteniamo di potere almeno dare loro la possibilità di spuntarla in un combattimento.\n\nIl Consiglio ha ricevuto rapporti segreti secondo cui ci sarebbero antichi manufatti, di cui la Concordia \nignora l'esistenza, sparsi su vari pianeti a disposizione di chi li conquisterà. La conoscenza di questi \nmanufatti ci concederà un vantaggio che ci metterà in condizione di proteggere le Grandi Astronavi e \nnegoziare con la Concordia da una posizione di forza.\n\n",
